name: Bug Report
description: Create a report to help us improve Tau
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Tau Version
      description: What version of ag_tau are you running?
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
    validations:
      required: true
