name: Rust CI (no_std)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: thumbv7m-none-eabi, wasm32-unknown-unknown

    - name: Build (Standard)
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Prove #![no_std] compatibility (Embedded)
      run: cargo build --target thumbv7m-none-eabi --verbose --no-default-features

    - name: Prove #![no_std] compatibility (WASM)
      run: cargo build --target wasm32-unknown-unknown --verbose --no-default-features
